           SELECT ARBEITER-FILE
               ASSIGN TO "arbeiter.dat"
               ORGANIZATION IS INDEXED
               RECORD KEY IS ARBEITER-ID
               ALTERNATE KEY IS ABTEILUNG-ID WITH DUPLICATES
               ALTERNATE KEY IS FAMILIE WITH DUPLICATES
               ALTERNATE KEY IS NAME WITH DUPLICATES
               ALTERNATE KEY IS SALARY WITH DUPLICATES
               ALTERNATE KEY IS EINSTELL-DATUM WITH DUPLICATES
               ACCESS MODE IS DYNAMIC.
